# Docs: https://github.com/release-drafter/release-drafter/
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  # the major label is not set automatically, but should be set explicitly if there are any breaking changes.

  - label: "minor"
    branch:
      - '/feature\/.+/'
  - label: "patch"
    branch:
      - '/bug\/.+/'
      - '/docs\/.+/'
      - '/fix\/.+/'
      - '/patch\/.+/'
      - '/dependabot\/.+/'

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
