name: Build and Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
    secrets:
      personalAccessToken:
        required: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Rewrite module name
        run: |
          templatedModuleName='github.com/lunarway/${{ '${{values.name}}' }}'
          validModuleName='github.com/lunarway/update'
          find ./template -type f -exec sed -i "s|$templatedModuleName|$validModuleName|" {} +

      # enable access to private Git repositories
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.personalAccessToken }}
        run: git config --global url."https://HamAstrochimp:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          cd template && go build ./...

      - name: Tests
        run: |
          cd template && go test -v ./...
